import "../app/global.css";
import Header from "../components/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning data-theme="light">
      <body>
        <Header />
        <main className="container mx-auto p-10">{children}</main>

        <footer className="text-gray-400 text-center text-small py-5"><small>Copyright &copy; {new Date().getFullYear()} - All rights reserved.</small></footer>
      </body>
    </html>
  );
}
